---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: prometheus-metrics
  namespace: prometheus
spec:
  folder: "Monitoring"
  resyncPeriod: 30m
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  configMapRef:
    name: prometheus-monitoring-dashboard
    key: json 