---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: prometheus-monitoring-dashboard
  namespace: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  grafanaCom:
    id: 19268
    # Revision 1 is usually the latest if not specified, 
    # but you can check grafana.com/dashboards/19268/revisions
    revision: 1